# Default values for fluentd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/google_containers/fluentd-elasticsearch
  tag: 1.23
  pullPolicy: IfNotPresent
service:
  name: fluentd
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi
volumeMounts:
- name: varlog
  mountPath: /var/log
- name: varlibdockercontainers
  mountPath: /var/lib/docker/containers
  readOnly: true
