# Default values for fluentd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: fluentd
replicaCount: 1
image:
  repository: gcr.io/google_containers/fluentd-elasticsearch
  tag: 1.23
  pullPolicy: Always
resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi
config:
  sample-config: "test"
secrets:
  sample-secret: "test"
#volumeMounts:
#- name: varlog
#  mountPath: /var/log
#- name: varlibdockercontainers
#  mountPath: /var/lib/docker/containers
#  readOnly: true
